app/Http/routes.php
<?php

Route::resource('granja', 'GranjaController');
Route::resource('galpon', 'GalponController');
Route::get('control/generaPDF/{id}',['as' => 'generaPDFC', 'uses' => 'ControlController@generaPDF']);
Route::resource('control', 'ControlController');
Route::get('produccion/generaPDF/{id}',['as' => 'generaPDFP', 'uses' => 'ProduccionController@generaPDF']);
Route::resource('produccion', 'ProduccionController');
Route::resource('faq', 'faqController');

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

// Admin
Route::get('admin',                 ['as' => 'admin',           'uses' => 'AdminController@index']);

//Route::get('admin/reporte',         ['as' => 'reporte',         'uses' =>  'AdminController@getReporte']);
//Route::post('admin/reporte',         ['as' => 'promedio',       'uses' =>  'AdminController@getPromedio']);

//Route::get('admin/ingreso-datos',   ['as' => 'ingreso_datos',   'uses' =>  'AdminController@getIngresoDatos']);

app/Http/Controllers/GalponController.php
<?php namespace AviReport\Http\Controllers;

use AviReport\Entities\Control;
use AviReport\Entities\Galpon;
use AviReport\Http\Requests;
use AviReport\Http\Controllers\Controller;

use Illuminate\Support\Facades\Session;
use Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Str;

class GalponController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
		$id = Session::get('id');
		$galpon = Galpon::find($id);
		return view('admin.galpon.index',compact('id','galpon'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{dd(Input::all());
		return view('admin/galpon/create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $inputs = Input::all();
        $num = (int) ($inputs['num_galpones']);

        $date = new \DateTime('NOW');
        $jsonControl = new \stdClass();
        $jsonControl->week = $inputs['week'];
        $jsonControl->last_update = $date->format('Y-m-d');
        $jsonControl->control = [];

        for($i = 0; $i < $num; $i++)
        {
            $dateFormat = $date->format('Y-m-d');
            $timeFormat = $date->format('H:i:s');
            $code = "GALP-".str_replace("-", "", $dateFormat)."-".str_replace(":", "", $timeFormat);

            $galpon = Galpon::create([
                'code'          => $code,
                'number_birds'  => $inputs['number_birds'],
                'description'   => $inputs['description'],
                'granja_id'     => $inputs['granja_id']
            ]);

            Control::create([
                'json_control'  => json_encode($jsonControl),
                'description'   => "Galpon de gallinas ponedoras",
                'type'          => 'ponedoras',
                'week'          => $inputs['week'],
                'galpon_id'     => $galpon->id
            ]);
        }

		return Redirect::back();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        $galpon = Galpon::find($id);
        $jsonControl = json_decode($galpon->control->json_control);

        $nextUpdate = new \DateTime($jsonControl->last_update);
        $nextUpdate->add(new \DateInterval('P7D'));

        $jsonControl->next_update = $nextUpdate->format('Y-m-d');

		return view('admin/galpon/show', compact('galpon', 'jsonControl'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$galpon = Galpon::find($id);
        return view('admin/galpon/edit', compact('galpon'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
        $inputs = Input::all();
        $galpon = Galpon::find($id);

        $request = $galpon->update($inputs);

        if ($request)
        {
            return Redirect::route('galpon.show', $id);
        }

        return Redirect::back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id, Request $request)
	{
        $galpon = Galpon::find($id);
        $galpon->delete();
        $message = "Galpón <b>".$galpon->code."</b> fue eliminado de la granja";

        if ($request->ajax())
        {
            return response()->json([
                'id'        => $id,
                'message'   => $message
            ]);
        }
	}

}

resources/views/admin/galpon/create.blade.php
@extends('layout_admin')

@section('content')
<section class="content-header">
    <h1>
        Crear Galpón
        <small>it all starts here</small>
        </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
    </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
		    {!! Form::open(['route' => 'galpon.store', 'method' => 'POST']) !!}
			    <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Nueva galpon</h3>
                    </div>
                    <div class="box-body with-border">
                        <div class="col-md-6">
                            <div class="form-group">
                                {!! Form::label('num_galpones', 'Numero de galpones') !!}
                                {!! Form::text('num_galpones', null, ['class' => 'form-control', 'placeholder' => 'Cantidad de galpones']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('number_birds', 'Numero de aves') !!}
                                {!! Form::text('number_birds', null, ['class' => 'form-control', 'placeholder' => '150']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {!! Form::label('description', 'Descripcion') !!}
                                {!! Form::text('description', null, ['class' => 'form-control', 'placeholder' => 'Ingrese descripción']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Crear galpones</button>
                        </div>
                    </div>
			    </div>
			{!! Form::close() !!}
		</div>
	</div>
</section>
@endsection

resources/views/admin/galpon/edit.blade.php
@extends('layout_admin')

@section('content')
<section class="content-header">
    <h1>
        Editar Galpón
        <small> </small>
        </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Granjas</a></li>
        <li><a href="#">Granja #</a></li>
        <li class="active">Editar {{ $galpon->code }}</li>
    </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
		    {!! Form::model($galpon, ['route' => ['galpon.update', $galpon->id], 'method' => 'PUT']) !!}
			    <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Nueva galpon</h3>
                    </div>
                    <div class="box-body with-border">
                        <div class="col-md-4">
                            <div class="form-group">
                                {!! Form::label('code', 'Código') !!}
                                {!! Form::text('code', null, ['class' => 'form-control', 'placeholder' => 'Cantidad de galpones', 'disabled' => 'true']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('number_birds', 'Numero de aves') !!}
                                {!! Form::input('number', 'number_birds', null, ['class' => 'form-control', 'placeholder' => 'Ingrese numero de aves']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('max_capacity', 'Capacidad máxima') !!}
                                {!! Form::input('number', 'max_capacity', null, ['class' => 'form-control', 'placeholder' => 'Ingrese valor']) !!}
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                {!! Form::label('description', 'Descripción') !!}
                                {!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Ingrese descripción', 'rows' => '8']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Guardar cambios</button>
                        </div>
                    </div>
			    </div>
			{!! Form::close() !!}
		</div>
	</div>
</section>
@endsection

resources/views/admin/galpon/index.blade.php
@extends('layout_admin')

@section('content')
    <section class="content-header">
       <p><h2>Galpon</h2> <h1>{{$galpon->code}}</h1></p>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-6 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>Analisis de Crecimiento</h3>

                        <p>Control Semanal de Crecimiento</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-institution"></i>
                    </div>
                    <a href="{{route('galpon.show',$id)}}" class="small-box-footer">Acceder <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-6 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>Analisis de Produccion</h3>

                        <p>Control Semanal de Produccion</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{{route('produccion.index',$id)}}" class="small-box-footer">Acceder<i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
    </section>
    @endsection

    @section('css-content')
            <!-- CSS -->
    @endsection


    @section('js-content')
            <!-- JS -->
@endsection