app/Http/routes.php
<?php

Route::resource('granja', 'GranjaController');
Route::resource('galpon', 'GalponController');
Route::get('control/generaPDF/{id}',['as' => 'generaPDFC', 'uses' => 'ControlController@generaPDF']);
Route::resource('control', 'ControlController');
Route::get('produccion/generaPDF/{id}',['as' => 'generaPDFP', 'uses' => 'ProduccionController@generaPDF']);
Route::resource('produccion', 'ProduccionController');
Route::resource('faq', 'faqController');

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

// Admin
Route::get('admin',                 ['as' => 'admin',           'uses' => 'AdminController@index']);

//Route::get('admin/reporte',         ['as' => 'reporte',         'uses' =>  'AdminController@getReporte']);
//Route::post('admin/reporte',         ['as' => 'promedio',       'uses' =>  'AdminController@getPromedio']);

//Route::get('admin/ingreso-datos',   ['as' => 'ingreso_datos',   'uses' =>  'AdminController@getIngresoDatos']);

app/Http/Controllers/GranjaController.php
<?php namespace AviReport\Http\Controllers;

use AviReport\Entities\Granja;
use AviReport\Http\Requests;
use AviReport\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;

class GranjaController extends Controller {

	public function __construct()
    {
        $this->middleware('auth');
    }


    /**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
        $user_id = Auth::user()->id;

        $granjas = \DB::table('granjas')
                        ->join('users', 'granjas.user_id', '=', 'users.id')
                        ->select('granjas.*', 'users.name as owner')
                        ->where('user_id', $user_id)
                        ->get();

		return view('admin/granja/index', compact('granjas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        return view('admin/granja/create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $inputs = Input::all();

        Granja::create([
            'name'          => $inputs['name'],
            'address'       => $inputs['address'],
            'number_phone'  => $inputs['number_phone'],
            'owner_name'    => $inputs['owner_name'],
            'user_id'       => Auth::user()->id
        ]);

        return Redirect::route('granja.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{/*
        \DB::table('granjas')
            ->join('users', 'granjas.user_id', '=', 'users.id')
            ->select('granjas.*', 'users.name as owner')
            ->where('user_id', $user_id)
            ->get();*/

        $granja = Granja::find($id);

        $galpones = \DB::table('granjas')
                    ->join('galpons', 'granjas.id', '=', 'galpons.granja_id')
                    ->select('galpons.*')
                    ->where('granjas.id', $id)
                    ->get();

        //dd($granja);

		return view('admin/granja/show', compact('granja', 'galpones'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $granja = Granja::find($id);

        return view('admin/granja/edit', compact('granja'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$inputs = Input::all();
        $granja = Granja::find($id);

        $request = $granja->update($inputs);

        if ($request)
        {
            return Redirect::route('granja.show', $id);
        }

        return Redirect::back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id, Request $request)
	{
        $granja = Granja::find($id);
        $granja->delete();

		if($request->ajax())
        {
            return response()->json([
                'id'    => $id,
                'message'  => "Granja <b>".$granja->name."</b> fue eliminada"
            ]);
        }
	}

}

resources/views/admin/granja/create.blade.php
@extends('layout_admin')

@section('content')
<section class="content-header">
    <h1>
        Crear Granja
        <small>it all starts here</small>
        </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Granja</a></li>
        <li class="active">Crear</li>
    </ol>
</section>
<section class="content">

	<div class="row">
		<div class="col-md-12">
		    {!! Form::open(['route' => 'granja.store', 'method' => 'POST']) !!}
			    <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Nueva granja</h3>
                    </div>
                    <div class="box-body with-border">
                        <div class="col-md-6">
                            <div class="form-group">
                                {!! Form::label('name', 'Nombre de Granja') !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Ingrese nombre de granja']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('owner_name', 'Propietario') !!}
                                {!! Form::text('owner_name', null, ['class' => 'form-control', 'placeholder' => 'Ingrese nombre de propietario']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {!! Form::label('address', 'Dirección') !!}
                                {!! Form::text('address', null, ['class' => 'form-control', 'placeholder' => 'Ingrese dirección']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('number_phone', 'Teléfono') !!}
                                {!! Form::text('number_phone', null, ['class' => 'form-control', 'placeholder' => 'Numero de teléfono']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Registrar</button>
                            <a class="btn btn-default" href="{{ url('granja') }}">Cancelar</a>
                        </div>
                    </div>
			    </div>
			{!! Form::close() !!}
		</div>
	</div>
</section>
@endsection

resources/views/admin/granja/edit.blade.php
@extends('layout_admin')

@section('content')
<section class="content-header">
    <h1>
        Editar Granja
        <small>it all starts here</small>
        </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Granja</a></li>
        <li class="active">Editar</li>
    </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
		    {!! Form::model($granja, ['route' => ['granja.update', $granja->id], 'method' => 'PUT']) !!}
			    <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Editar información</h3>
                    </div>
                    <div class="box-body with-border">
                        <div class="col-md-6">
                            <div class="form-group">
                                {!! Form::label('name', 'Nombre de Granja') !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Ingrese nombre de granja']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('owner_name', 'Propietario') !!}
                                {!! Form::text('owner_name', null, ['class' => 'form-control', 'placeholder' => 'Ingrese nombre de propietario']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {!! Form::label('address', 'Dirección') !!}
                                {!! Form::text('address', null, ['class' => 'form-control', 'placeholder' => 'Ingrese dirección']) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('number_phone', 'Teléfono') !!}
                                {!! Form::text('number_phone', null, ['class' => 'form-control', 'placeholder' => 'Numero de teléfono']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                            <a class="btn btn-default" href="{{ url('granja') }}">Cancelar</a>
                        </div>
                    </div>
			    </div>
		    {!! Form::close() !!}
		</div>
	</div>

</section>
@endsection

resources/views/admin/granja/index.blade.php
@extends('layout_admin')

@section('content')
<section class="content-header">
    <h1>Granjas</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Granjas</a></li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('granja.create') }}" class="btn btn-primary btn-block margin-bottom">Nueva Granja</a>
            <div class="box box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">Granjas Supervisadas</h3>
                </div>
                <div class="box-body no-padding">
                    <div class="nav nav-pills nav-stacked">
                        <li  class="">
                            <a href="#">
                                <i class="fa fa-server"></i> Total
                                <span class="label label-default pull-right">{{ sizeof($granjas) }}</span>
                            </a>
                        </li>
                        <!--<li>
                            <a href="#">
                                <i class="fa fa-circle text-orange"></i> Crecimiento?
                                <span class="label label-default pull-right">{{ sizeof($granjas) }}</span>
                            </a>
                        </li>-->
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Listado de Granjas Supervisadas</h3>
                    <div class="box-tools pull-right">
                        <div class="has-feedback">
                            <input type="text" class="form-control input-sm" placeholder="Buscar Granja">
                            <span class="glyphicon glyphicon-search form-control-feedback"></span>
                        </div>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <th>Código</th>
                            <th>Nombre</th>
                            <th>Propietario</th>
                            <th>Teléfono</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            @foreach($granjas as $index => $granja)
                                <tr data-id="{{ $granja->id  }}">
                                    <td> {{ $granja->id }} </td>
                                    <td><a href="{{ route('granja.show', $granja->id) }}"> {!! $granja->name !!} </a>  </td>
                                    <td> {!! $granja->owner_name !!} </td>
                                    <td> {!! $granja->number_phone !!} </td>
                                    <td>
                                        <a class="btn btn-xs btn-primary" href="{{ route('granja.show', $granja->id) }}">Ingresar</a>
                                        <a class="btn btn-xs btn-info" href="{{ route('granja.edit', $granja->id) }}">Editar</a>
                                        <a class="btn btn-xs btn-danger">Eliminar</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

{!! Form::open(['route' => ['granja.destroy', ':GRANJA_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
{!! Form::close() !!}

@endsection

@section('js-content')
<script src="{{ asset('plugins/bootstrap-notify/bootstrap-notify.min.js') }}" type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function() {

    $('.btn-danger').click(function() {

        if (!confirm('¿Esta seguro de eliminar la granja seleccionada?'))
        {
            return;
        }

        var row = $(this).parents('tr');
        var id = row.data('id');
        var form = $('#form-delete');
        var url = form.attr('action').replace(':GRANJA_ID', id);
        var data = form.serialize();

        $.post(url, data, function(response) {
            $.notify({
                title: "<b>Mensaje de AviReport:</b> </br> ",
                message: response.message

            }, {
                type: 'warning',
                placement: {
                    from: "bottom",
                    align: "right"
                }
            });

            row.fadeOut();
        }).fail(function() {
            $.notify({
                title: "Error </br>",
                message: "No se pudo eliminar la granja seleccionada"

            }, {
                type: 'info',
                placement: {
                    from: "bottom",
                    align: "right"
                }
            });
        });
    });
});
</script>
@endsection

resources/views/admin/granja/show.blade.php
@extends('layout_admin')

@section('content')
<section class="content-header">
    <h1>
        Granja {{ $granja->name }}
        </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('granja.index') }}"><i class="fa fa-home"></i> Granjas</a></li>
        <li class="active"> {{ $granja->name }}</li>
    </ol>
</section>
<section class="content">
    <div class="row">


	    <div class="col-md-3">
	        <button id="add_galpon" class="btn btn-primary btn-block margin-bottom">Nuevo Galpon</button>
	        <div class="box box-default">
	            <div class="box-header with-border">
	                <h3 class="box-title">Información</h3>
	                <div class="box-tools pull-right">
	                    <a href="{{ route('granja.edit', $granja->id) }}" class="btn btn-box-tool"><i class="fa fa-edit fa-2x"></i></a>
	                </div>
	            </div>
	            <div class="box-body">
	                <ul class="list-group">
	                    <li class="list-group-item"> <b>Nombre Granja: </b> <br/>{!! $granja->name !!} </li>
	                    <li class="list-group-item"> <b>Propietario:</b> <br/>{!! $granja->owner_name !!}</li>
	                    <li class="list-group-item"> <b>Teléfono:</b> <br/>{!! $granja->number_phone !!}</li>
	                    <li class="list-group-item"> <b>Dirección:</b> <br/>{!! $granja->address !!}</li>
	                    <li class="list-group-item"> <b>Numero de galpones:</b> <br/>{!! count($galpones) !!}</li>
	                </ul>
	            </div>
	        </div>
	    </div>
	    <div class="col-md-9">
	        <div class="row hidden" id="form_galpon">
                <div class="col-md-12">
                    <div class="box box-default">
                        <div class="box-body">
                            {!! Form::open(['route' => 'galpon.store', 'method' => 'POST']) !!}
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="number_birds">Cantida de aves</label>
                                        <input name="number_birds" type="number" class="form-control" placeholder="0" required/>
                                    </div>
                                    <div class="form-group">
                                        <label for="num_galpones">Numero de galpones</label>
                                        <input name="num_galpones" type="number" class="form-control" value="1" required/>
                                    </div>
                                    <div class="form-group">
                                        <label for="week">Semana actual de crecimiento</label>
                                        <select name="week" class="form-control" id="week">
                                            @for($i = 1; $i <= 90; $i++)
                                                <option>{{ $i }}</option>
                                            @endfor
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label for="description">Descripción</label>
                                        <textarea name="description" rows="9" class="form-control" placeholder="Ejm: Gallinas ponedoras" required></textarea>
                                    </div>
                                    <input type="hidden" name="granja_id" value="{!! $granja->id !!}" />
                                    <button id="cancelar" class="btn btn-default pull-right">Cancelar</button>
                                    <button type="submit" class="btn btn-primary pull-right">Guardar</button>
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
	        </div>
	        <div class="box box-default">
	            <div class="box-header with-border">
	                <h3 class="box-title">Galpones</h3>
	            </div>
	            <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <th>#</th>
                            <th>Codigo</th>
                            <th>Numero de aves</th>
                            <th>Descripción</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            @foreach($galpones as $index => $galpon)
                            <tr data-id="{{ $galpon->id }}">
                                <td> {!! $index + 1 !!}</td>
                                <td> <a href="{{ route('galpon.index', $galpon->id) }}">{!! $galpon->code !!}</a></td>
                                {{Session::put('id',$galpon->id)}}
                                <td> {!! $galpon->number_birds !!}</td>
                                <td> {!! $galpon->description !!}</td>
                                <td>
                                    <a class="btn btn-xs btn-info" href="{{ route('galpon.edit', $galpon->id) }}">Editar</a>
                                    <a class="btn btn-xs btn-danger">Eliminar</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
	            </div>
	        </div>
        </div>
        <!-- /.end -->
    </div>
</section>

{!! Form::open(['route' => ['galpon.destroy', ':GALPON_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
{!! Form::close() !!}

@endsection

@section('css-content')

@endsection

@section('js-content')

<script src="{{ asset('plugins/bootstrap-notify/bootstrap-notify.min.js') }}" type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function () {

    $('.btn-danger').click(function (e) {

        if (!confirm('Esta seguro de eliminar el galpon seleccionado?'))
        {
            return;
        }

        var row = $(this).parents('tr');
        var id = row.data('id');
        var form = $('#form-delete');
        var url = form.attr('action').replace(':GALPON_ID', id);
        var data = form.serialize();

        $.post(url, data, function(result) {
            $.notify({
                title: "<b>Mensaje de AviReport:</b> </br> ",
                message: result.message

            }, {
                type: 'warning',
                placement: {
                    from: "bottom",
                    align: "right"
                }
            });

            row.fadeOut();

        }).fail(function() {
            $.notify({
                title: "Error </br>",
                message: "No se pudo eliminar el galpon seleccionado"

            }, {
                type: 'info',
                placement: {
                    from: "bottom",
                    align: "right"
                }
            });
        });

    });

    $('#add_galpon').click(function() {
        $('#form_galpon').removeClass('hidden');
    });

    $('#cancelar').click(function() {
        $('#form_galpon').addClass('hidden');
    });
});
</script>
@endsection